### ISSUE TITLE
Entregar la práctica 2

### ISSUE THREAD

**Issue by ivanortegaalba** [CongressWebDevelopers/web-congreso#22]
Añadir dinamismo con JS:
- submenús que aparecen o desaparecen (también se puede hacer en CSS);
- una zona con un slider donde los logos de los patrocinadores vayan rotando;
- un formulario de contacto con un botón “Enviar”.
  
  El formulario de contacto deberá tener los siguientes campos:
  - Nombre y Apellidos
  - E-mail
  - Texto del mensaje
    Al hacer clic en “Enviar” se deberá validar que el E-mail es, al menos, formalmente correcto (xxxx@xxxx.xx), y, una vez cerciorados de la corrección de los datos, debe mostrar un mensaje de agradecimiento por el contacto (por ahora no lo enviaremos al servidor).

**Comment by joseluisfdezbueno** [comment]
La práctica está lista, falta hacer un merge de mi rama a la master, y enviar el .zip

**Comment by ivanortegaalba** [comment]
@jota-ele256 haz un pull request

**Comment by joseluisfdezbueno** [comment]
@ivanortegaalba , pull request hecho

**Comment by joseluisfdezbueno** [comment]
pone que puedo hacer el merge sin problemas

**Comment by ivanortegaalba** [comment]
si pero no lo hagas ya lo he hecho yo en local @jota-ele256

**Comment by joseluisfdezbueno** [comment]
ok @ivanortegaalba Tengo que hacer yo la entrega al swad, no?

**Comment by ivanortegaalba** [comment]
@jota-ele256 si, he cambiado unas ultimas cosas. RECUERDA, LA VERSION VÁLIDA ES LA DE LA RAMA MASTER.
Para cambiarte a esta solo tienes que hacer:

```
git checkout master
```

Y no olvides despues volver a tu rama con 

```
git checkout Jose
```

**Comment by ivanortegaalba** [comment]
@jota-ele256 tambien he hecho algunos cambios de aspecto en el formulario. :)

**Comment by ivanortegaalba** [comment]
Am y descarga los cambios con 

```
git pull origin master
```
