### ISSUE TITLE
Tareas

### ISSUE THREAD

**Issue by joseluisfdezbueno** [CongressWebDevelopers/web-congreso#4]
-Inicio
-Patrocinadores
-Inscripción
-Actividades
-Programa
-Información ciudad
-Información etsiit

Me parece bien lo que propones, yo salgo hoy a las 19.30, si estas por alli lo vemos; si no nos vemos, asigna tú mismo como lo veas conveniente; y ya cuando llegue a casa me pongo con ello.

**Comment by ivanortegaalba** [comment]
- Hay que hacer el html de cada uno de ellos. Vamos a asignarnos cada uno un archivo, y luego desde el inicio se lincan y se copia toda la cabecera. 
- La cabecera está subida ya, en el index.html. Hay que copiarla como está en cada uno de los archivos que se vayan a hacer.
- En inscripción habría que hacer un formulario, si quieres me lo asigno yo, que tiene un poco de más curro. 
- El programa, como todavía no lo sabe el cliente, le ponemos un próximamente
  y sobre la información de la ciudad y tal, no se, poner cuatro cosas. Nos podemos asignar cada uno una de las dos informaciones.
- Actividades hay dos en principio, por lo que habría que hacer 2 páginas:
  - Visita a la Alhambra
  - Visita a Sierra Nevada
    La estructura en el menu principal quedaría de la siguiente manera:
- Inicio
- Patrocinadores
- Inscripción
- Actividades
  - Visita a la Alhambra
  - Visita a Sierra Nevada
- Programa
- Información
  - Información ciudad
  - Información ETSIIT

**Comment by ivanortegaalba** [comment]
Cierra este issue @jota-ele256 ;)
